### ISSUE TITLE
Wrong optimizations for 64 bit CPUs

### ISSUE THREAD

**Issue by AngeloG** [samgreen/CGVector-Awesome#2]
On 64 bit CPUs, some functions return invalid values due to the optimization that seems to be specifically made for 32 bit. `CGVectorMultiplyByScalar` for example.

**Comment by samgreen** [comment]
Can you elaborate on this for me? Would love to fix it, also I will happily accept a pull request.

**Comment by samgreen** [comment]
@AngeloG Found the problem. It's due to CGFloat changing types of 64bit architecture. Resolving the issue now, will release ASAP.

**Comment by samgreen** [comment]
Fixed!

**Comment by AngeloG** [comment]
Awesome! :+1:

**Comment by AngeloG** [comment]
[This](https://github.com/samgreen/CGVector-Awesome/commit/a48c739be8663cc073ff583738b1c899ac897e36) shows an empty change, are you sure you pushed it correctly?

**Comment by samgreen** [comment]
Doh! Thanks noticing. Will repush in an hour or so.

**Comment by samgreen** [comment]
@AngeloG Thanks for your patience on this. The header file and Readme are now updated.

I would love any additional feedback you have on this library, it's worked well for me in a few games, but I'm always looking to improve it.

**Comment by AngeloG** [comment]
Awesome, thanks! We're using it for a game we'll be releasing on the app store soonish.

Personally I've added a function CGVectorFromPoint (which converts a CGPoint to a CGVector), but perhaps this is already implemented by Apple somewhere that I've missed. It's been very helpful so far!

**Comment by samgreen** [comment]
@AngeloG Please submit a pull request with your additional features, I'd love to merge them in!
