### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Mazyod** [samgreen/CGVector-Awesome#6]
Doesn't seem to me like this code contains any kind of license. Would be great to have that so I can reuse it as appropriate.

Thanks

**Comment by AngeloG** [comment]
I propose MIT license, or even public domain.

**Comment by samgreen** [comment]
Thanks for the feedback! 

I'm licensing this under zLib which is compatible with GPL, and may be distributed commercially. It's one of the more permissive licenses, in addition to being open source compatible.

**Comment by AngeloG** [comment]
That works! Nice.
